name: publish

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the project
        uses: actions/checkout@v2
      - name: set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - run: |
          RELEASE_VERSION=${RELEASE_VERSION#"v"}
          echo $RELEASE_VERSION
          sed -i -e "s/\"version\":.*/\"version\": \""$RELEASE_VERSION"\","/g package.json
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@synergatika'
      - name: Install dependencies
        run: npm install
      - run: npm config set @synergatika:registry https://npm.pkg.github.com
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
